export const projectsData = [
  {
    id: 1,
    name: "Hotel",
    tools: ["React", "Sass", "ContextAPI"],
    apiLink: "No API",
    host: "Netlify",
    inspiredBy: "Coddint Addict",
    inspiredByLink: "http",
    colors: ["#ccc", "#347d32"],
    auth: "No",
    link: "http.netlify",
    githubLink: "github.com",
    image: "images/hotels.png",
    description:
      "This is a hotel reserve like website that has 3 static pages, with multiple dynamic pages for rooms that can be sorted by type and(or) price!.All datas are dummy and There is also a (fake)form for sign in/sign out.",
  },
  {
    id: 2,
    name: "CryptoCurrency",
    tools: ["React", "Sass", "3rdParty API", "Redux toolkit"],
    apiLink: "RapidAPI",
    host: "https://www.google.com/",
    inspiredBy: "JS Mastery",
    inspiredByLink: "http",
    colors: ["#ccc", "#347d32"],
    auth: "No",
    link: "http.netlify",
    githubLink: "github.com",
    image: "images/crypto.png",
    description:
      "Live news about crypto price, crypto exchange, last crypto news and much more, You can check and study the most famous cryptos during 24hours to 5years!, There is capability to change them between green and blue",
  },
  {
    id: 3,
    name: "Zflix",
    tools: ["React", "Sass", "3rdParty API", "Redux toolkit"],
    apiLink: "RapidAPI",
    host: "Netlify",
    inspiredBy: "Coddint Addict",
    inspiredByLink: "http",
    colors: ["#ccc", "#347d32"],
    auth: "Yes",
    link: "http.netlify",
    githubLink: "github.com",
    image: "images/zflix.png",
    description:
      "Show you highest Top250 rated moives and series based on IMDb score. also you can access to much information about awards,casts & ... of every movies. Live theatre has been shown on theatre page. This app is using google auth for authentication.",
  },
  {
    id: 4,
    name: "MemoryCard",
    tools: ["React", "Sass", "Restful API", "Redux toolkit"],
    apiLink: "",
    host: "Netlify",
    inspiredBy: "Coddint Addict",
    inspiredByLink: "http",
    colors: ["#ccc", "#347d32"],
    auth: "Yes",
    link: "http.netlify",
    githubLink: "github.com",
    image: "images/memorycard.png",
    description:
      "Mern stack application that you can create and save your memory card with 3 required fields. you can customize your card and add as more as fields you wish. Wishlist page can help you save favorite cards seprately.",
  },
];
