export const projectsData = [
  {
    id: 1,
    name: "Hotel",
    tools: ["React", "Sass", "ContextAPI", "ReactIcons"],
    apiLink: "No API",
    host: "Firebase",
    inspiredBy: "Coddint Addict",
    inspiredByLink: "https://www.youtube.com/watch?v=ScDWrogElmo&t=17849s",
    colors: ["#fd746c", "#ff9068", "#f46b45", "#eea849", "#eef2f3", "#29323c"],
    auth: "No",
    link: "https://beach-hotels.web.app/",
    githubLink: "https://github.com/FarNys/Beach-Hotels",
    image: "images/hotels.png",
    description:
      "This is a hotel reserve like website that has 3 static pages, with multiple dynamic pages for rooms that can be sorted by type and(or) price!. All datas are dummy and the sign in/sign up form is for UI and doesn't have functionality.",
  },
  {
    id: 2,
    name: "CryptoCurrency",
    tools: [
      "React",
      "Sass",
      "3rdParty API",
      "Redux toolkit",
      "ReactIcons",
      "Material UI(Icons)",
      "Material UI(Components)",
    ],
    apiLink: "https://developers.coinranking.com/api",
    host: "Netlify",
    inspiredBy: "JS Mastery",
    inspiredByLink: "https://www.youtube.com/watch?v=9DDX3US3kss",
    colors: ["#3f3f3f", "#93f9b9", "#3ca55c", "#12d8fa", "#1fa2ff"],
    auth: "No",
    link: "https://cryptoindepth.netlify.app/",
    githubLink: "https://github.com/FarNys/CryptoCurrency",
    image: "images/crypto.png",
    description:
      "Live news about crypto price, crypto exchange, last crypto news and much more, You can analyze and study the most famous cryptos in the period of 24hours to 5years!, simple UI/UX with capability of change theme between light-green and light-blue",
  },
  {
    id: 3,
    name: "Zflix",
    tools: [
      "React",
      "Sass",
      "3rdParty API",
      "Redux toolkit",
      "ReactIcons",
      "Material UI(Icons)",
      "unDraw",
    ],
    apiLink: "https://imdb-api.com/",
    host: "Firebase",
    inspiredBy: "",
    inspiredByLink: "",
    colors: ["#4e54c8", "#8f94fb", "#333333", "#8e2de2", "#d5d8d8", "#1f1c2c"],
    auth: "Yes",
    link: "https://zflix-77be9.web.app/",
    githubLink: "https://github.com/FarNys/Zflix",
    image: "images/zflix.png",
    description:
      "Show you highest Top250 rated moives and series based on IMDb score. also you can access to much information about awards,casts & ... of every movies. Live theatre has been shown on theatre page. This app is using google auth for authentication.",
  },
  {
    id: 4,
    name: "MemoryCard",
    tools: [
      "React",
      "Sass",
      "Restful API",
      "Redux toolkit",
      "mongoDb",
      "NodeJS",
      "Express",
    ],
    apiLink: "",
    host: "Netlify,Heroku",
    inspiredBy: "",
    inspiredByLink: "",
    colors: ["#020024", "#090979", "#00d4ff", "#fefefe", "#d3d3d3"],
    auth: "Yes",
    link: "https://memorycard2.netlify.app/",
    githubLink: "https://github.com/FarNys/MC_FRONTEND",
    image: "images/memorycard.png",
    description:
      "MERN stack application that you can create and save your memory card with 3 required fields. you can customize your card and add as more as fields you wish. Wishlist page can help you save favorite cards seprately.",
  },
];
